---
- hosts: all
  user: ie-user
  sudo: yes
  vars:
    mysql_root_password: kakikukeko
  tasks:
    - name: install zabbix
      yum: name={{ item }} state=installed
      with_items:
        - http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-web-japanese
        - zabbix-agent
        - mariadb-server
        - MySQL-python

    - name: mariadb settings
      copy: src=server.cnf dest=/etc/my.cnf.d/server.cnf owner=root group=root mode=644

    - name: MariaDB started and enabled
      service: name=mariadb state=started enabled=yes

    - name: root account settings
      mysql_user: name=root host=localhost password="{{ mysql_root_password }}"
