---
- hosts: all
  user: 
  sudo: yes
  tasks:
    - name: install zabbix
      yum: name={{ item }} state=installed
      with_items:
        - http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-web-japanese
        - zabbix-agent
        - mariadb-server
